addons:
  apt_packages:
    - lib32z1
    - lib32stdc++6
    - p7zip-full
    - lftp

language: c

env:
  - SOURCEMOD=1.8
  - SOURCEMOD=1.9

script:
    - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash build.sh $SOURCEMOD $FTP_HOST $FTP_USER $FTP_PSWD ${TRAVIS_COMMIT::7}; fi'
